name: build
on:
  push:
    branches:
      - master

env:
  DIST_DIR: dist

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Run test
        run: yarn test

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run semantic-release

      - name: Production build
        run: yarn build

      - name: Upload built files
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ${{ env.DIST_DIR }}
